"""Typed async Redis protocol used by repository implementations."""

from __future__ import annotations

from typing import Protocol


class AsyncRedisClient(Protocol):
    async def get(self, key: str) -> object: ...

    async def set(self, key: str, value: str) -> object: ...

    async def sadd(self, key: str, *values: str) -> int: ...

    async def srem(self, key: str, *values: str) -> int: ...

    async def smembers(self, key: str) -> set[object]: ...

    async def scard(self, key: str) -> int: ...

    async def hset(self, key: str, field: str, value: str) -> int: ...

    async def hget(self, key: str, field: str) -> object: ...

    async def hdel(self, key: str, *fields: str) -> int: ...

    async def delete(self, *keys: str) -> int: ...

    async def exists(self, key: str) -> int: ...
