/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as WorkersIndexRouteImport } from "./routes/workers/index"
import { Route as FunctionsIndexRouteImport } from "./routes/functions/index"
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index"
import { Route as ApisIndexRouteImport } from "./routes/apis/index"
import { Route as AdminIndexRouteImport } from "./routes/admin/index"
import { Route as ActivityIndexRouteImport } from "./routes/activity/index"
import { Route as WorkersNameIndexRouteImport } from "./routes/workers/$name/index"
import { Route as JobsJobIdIndexRouteImport } from "./routes/jobs/$jobId/index"
import { Route as FunctionsNameIndexRouteImport } from "./routes/functions/$name/index"
import { Route as ApisNameIndexRouteImport } from "./routes/apis/$name/index"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIndexRoute = WorkersIndexRouteImport.update({
  id: "/workers/",
  path: "/workers/",
  getParentRoute: () => rootRouteImport,
} as any)
const FunctionsIndexRoute = FunctionsIndexRouteImport.update({
  id: "/functions/",
  path: "/functions/",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/dashboard/",
  path: "/dashboard/",
  getParentRoute: () => rootRouteImport,
} as any)
const ApisIndexRoute = ApisIndexRouteImport.update({
  id: "/apis/",
  path: "/apis/",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/admin/",
  path: "/admin/",
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIndexRoute = ActivityIndexRouteImport.update({
  id: "/activity/",
  path: "/activity/",
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersNameIndexRoute = WorkersNameIndexRouteImport.update({
  id: "/workers/$name/",
  path: "/workers/$name/",
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdIndexRoute = JobsJobIdIndexRouteImport.update({
  id: "/jobs/$jobId/",
  path: "/jobs/$jobId/",
  getParentRoute: () => rootRouteImport,
} as any)
const FunctionsNameIndexRoute = FunctionsNameIndexRouteImport.update({
  id: "/functions/$name/",
  path: "/functions/$name/",
  getParentRoute: () => rootRouteImport,
} as any)
const ApisNameIndexRoute = ApisNameIndexRouteImport.update({
  id: "/apis/$name/",
  path: "/apis/$name/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/activity/": typeof ActivityIndexRoute
  "/admin/": typeof AdminIndexRoute
  "/apis/": typeof ApisIndexRoute
  "/dashboard/": typeof DashboardIndexRoute
  "/functions/": typeof FunctionsIndexRoute
  "/workers/": typeof WorkersIndexRoute
  "/apis/$name/": typeof ApisNameIndexRoute
  "/functions/$name/": typeof FunctionsNameIndexRoute
  "/jobs/$jobId/": typeof JobsJobIdIndexRoute
  "/workers/$name/": typeof WorkersNameIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/activity": typeof ActivityIndexRoute
  "/admin": typeof AdminIndexRoute
  "/apis": typeof ApisIndexRoute
  "/dashboard": typeof DashboardIndexRoute
  "/functions": typeof FunctionsIndexRoute
  "/workers": typeof WorkersIndexRoute
  "/apis/$name": typeof ApisNameIndexRoute
  "/functions/$name": typeof FunctionsNameIndexRoute
  "/jobs/$jobId": typeof JobsJobIdIndexRoute
  "/workers/$name": typeof WorkersNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/activity/": typeof ActivityIndexRoute
  "/admin/": typeof AdminIndexRoute
  "/apis/": typeof ApisIndexRoute
  "/dashboard/": typeof DashboardIndexRoute
  "/functions/": typeof FunctionsIndexRoute
  "/workers/": typeof WorkersIndexRoute
  "/apis/$name/": typeof ApisNameIndexRoute
  "/functions/$name/": typeof FunctionsNameIndexRoute
  "/jobs/$jobId/": typeof JobsJobIdIndexRoute
  "/workers/$name/": typeof WorkersNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/activity/"
    | "/admin/"
    | "/apis/"
    | "/dashboard/"
    | "/functions/"
    | "/workers/"
    | "/apis/$name/"
    | "/functions/$name/"
    | "/jobs/$jobId/"
    | "/workers/$name/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/activity"
    | "/admin"
    | "/apis"
    | "/dashboard"
    | "/functions"
    | "/workers"
    | "/apis/$name"
    | "/functions/$name"
    | "/jobs/$jobId"
    | "/workers/$name"
  id:
    | "__root__"
    | "/"
    | "/activity/"
    | "/admin/"
    | "/apis/"
    | "/dashboard/"
    | "/functions/"
    | "/workers/"
    | "/apis/$name/"
    | "/functions/$name/"
    | "/jobs/$jobId/"
    | "/workers/$name/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityIndexRoute: typeof ActivityIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApisIndexRoute: typeof ApisIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  FunctionsIndexRoute: typeof FunctionsIndexRoute
  WorkersIndexRoute: typeof WorkersIndexRoute
  ApisNameIndexRoute: typeof ApisNameIndexRoute
  FunctionsNameIndexRoute: typeof FunctionsNameIndexRoute
  JobsJobIdIndexRoute: typeof JobsJobIdIndexRoute
  WorkersNameIndexRoute: typeof WorkersNameIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/workers/": {
      id: "/workers/"
      path: "/workers"
      fullPath: "/workers/"
      preLoaderRoute: typeof WorkersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/functions/": {
      id: "/functions/"
      path: "/functions"
      fullPath: "/functions/"
      preLoaderRoute: typeof FunctionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dashboard/": {
      id: "/dashboard/"
      path: "/dashboard"
      fullPath: "/dashboard/"
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apis/": {
      id: "/apis/"
      path: "/apis"
      fullPath: "/apis/"
      preLoaderRoute: typeof ApisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/": {
      id: "/admin/"
      path: "/admin"
      fullPath: "/admin/"
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/activity/": {
      id: "/activity/"
      path: "/activity"
      fullPath: "/activity/"
      preLoaderRoute: typeof ActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/workers/$name/": {
      id: "/workers/$name/"
      path: "/workers/$name"
      fullPath: "/workers/$name/"
      preLoaderRoute: typeof WorkersNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/jobs/$jobId/": {
      id: "/jobs/$jobId/"
      path: "/jobs/$jobId"
      fullPath: "/jobs/$jobId/"
      preLoaderRoute: typeof JobsJobIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/functions/$name/": {
      id: "/functions/$name/"
      path: "/functions/$name"
      fullPath: "/functions/$name/"
      preLoaderRoute: typeof FunctionsNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/apis/$name/": {
      id: "/apis/$name/"
      path: "/apis/$name"
      fullPath: "/apis/$name/"
      preLoaderRoute: typeof ApisNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityIndexRoute: ActivityIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApisIndexRoute: ApisIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  FunctionsIndexRoute: FunctionsIndexRoute,
  WorkersIndexRoute: WorkersIndexRoute,
  ApisNameIndexRoute: ApisNameIndexRoute,
  FunctionsNameIndexRoute: FunctionsNameIndexRoute,
  JobsJobIdIndexRoute: JobsJobIdIndexRoute,
  WorkersNameIndexRoute: WorkersNameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
