/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkersIndexRouteImport } from './routes/workers/index'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as FunctionsIndexRouteImport } from './routes/functions/index'
import { Route as ApisIndexRouteImport } from './routes/apis/index'
import { Route as WorkersIdRouteImport } from './routes/workers/$id'
import { Route as RunsIdRouteImport } from './routes/runs/$id'
import { Route as FunctionsNameRouteImport } from './routes/functions/$name'
import { Route as ApisMethodSplatRouteImport } from './routes/apis/$method.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIndexRoute = WorkersIndexRouteImport.update({
  id: '/workers/',
  path: '/workers/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const FunctionsIndexRoute = FunctionsIndexRouteImport.update({
  id: '/functions/',
  path: '/functions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApisIndexRoute = ApisIndexRouteImport.update({
  id: '/apis/',
  path: '/apis/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIdRoute = WorkersIdRouteImport.update({
  id: '/workers/$id',
  path: '/workers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIdRoute = RunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FunctionsNameRoute = FunctionsNameRouteImport.update({
  id: '/functions/$name',
  path: '/functions/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApisMethodSplatRoute = ApisMethodSplatRouteImport.update({
  id: '/apis/$method/$',
  path: '/apis/$method/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/functions/$name': typeof FunctionsNameRoute
  '/runs/$id': typeof RunsIdRoute
  '/workers/$id': typeof WorkersIdRoute
  '/apis/': typeof ApisIndexRoute
  '/functions/': typeof FunctionsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/workers/': typeof WorkersIndexRoute
  '/apis/$method/$': typeof ApisMethodSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/functions/$name': typeof FunctionsNameRoute
  '/runs/$id': typeof RunsIdRoute
  '/workers/$id': typeof WorkersIdRoute
  '/apis': typeof ApisIndexRoute
  '/functions': typeof FunctionsIndexRoute
  '/runs': typeof RunsIndexRoute
  '/workers': typeof WorkersIndexRoute
  '/apis/$method/$': typeof ApisMethodSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/functions/$name': typeof FunctionsNameRoute
  '/runs/$id': typeof RunsIdRoute
  '/workers/$id': typeof WorkersIdRoute
  '/apis/': typeof ApisIndexRoute
  '/functions/': typeof FunctionsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/workers/': typeof WorkersIndexRoute
  '/apis/$method/$': typeof ApisMethodSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/functions/$name'
    | '/runs/$id'
    | '/workers/$id'
    | '/apis/'
    | '/functions/'
    | '/runs/'
    | '/workers/'
    | '/apis/$method/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/functions/$name'
    | '/runs/$id'
    | '/workers/$id'
    | '/apis'
    | '/functions'
    | '/runs'
    | '/workers'
    | '/apis/$method/$'
  id:
    | '__root__'
    | '/'
    | '/functions/$name'
    | '/runs/$id'
    | '/workers/$id'
    | '/apis/'
    | '/functions/'
    | '/runs/'
    | '/workers/'
    | '/apis/$method/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FunctionsNameRoute: typeof FunctionsNameRoute
  RunsIdRoute: typeof RunsIdRoute
  WorkersIdRoute: typeof WorkersIdRoute
  ApisIndexRoute: typeof ApisIndexRoute
  FunctionsIndexRoute: typeof FunctionsIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
  WorkersIndexRoute: typeof WorkersIndexRoute
  ApisMethodSplatRoute: typeof ApisMethodSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/': {
      id: '/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof WorkersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/functions/': {
      id: '/functions/'
      path: '/functions'
      fullPath: '/functions/'
      preLoaderRoute: typeof FunctionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apis/': {
      id: '/apis/'
      path: '/apis'
      fullPath: '/apis/'
      preLoaderRoute: typeof ApisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/$id': {
      id: '/workers/$id'
      path: '/workers/$id'
      fullPath: '/workers/$id'
      preLoaderRoute: typeof WorkersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$id': {
      id: '/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof RunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/functions/$name': {
      id: '/functions/$name'
      path: '/functions/$name'
      fullPath: '/functions/$name'
      preLoaderRoute: typeof FunctionsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apis/$method/$': {
      id: '/apis/$method/$'
      path: '/apis/$method/$'
      fullPath: '/apis/$method/$'
      preLoaderRoute: typeof ApisMethodSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FunctionsNameRoute: FunctionsNameRoute,
  RunsIdRoute: RunsIdRoute,
  WorkersIdRoute: WorkersIdRoute,
  ApisIndexRoute: ApisIndexRoute,
  FunctionsIndexRoute: FunctionsIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
  WorkersIndexRoute: WorkersIndexRoute,
  ApisMethodSplatRoute: ApisMethodSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
