"""initial migration

Revision ID: eb93a8d16e01
Revises: 
Create Date: 2026-02-05 16:56:55.433739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb93a8d16e01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('function', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Float(), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('kwargs', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_history_created_at', 'job_history', ['created_at'], unique=False)
    op.create_index('ix_job_history_function', 'job_history', ['function'], unique=False)
    op.create_index('ix_job_history_status', 'job_history', ['status'], unique=False)
    op.create_index('ix_job_history_worker_id', 'job_history', ['worker_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('storage_backend', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=700), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_artifacts_job_id', 'artifacts', ['job_id'], unique=False)
    op.create_index('ix_artifacts_name', 'artifacts', ['name'], unique=False)
    op.create_index('ix_artifacts_storage', 'artifacts', ['storage_backend', 'storage_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_artifacts_storage', table_name='artifacts')
    op.drop_index('ix_artifacts_name', table_name='artifacts')
    op.drop_index('ix_artifacts_job_id', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('ix_job_history_worker_id', table_name='job_history')
    op.drop_index('ix_job_history_status', table_name='job_history')
    op.drop_index('ix_job_history_function', table_name='job_history')
    op.drop_index('ix_job_history_created_at', table_name='job_history')
    op.drop_table('job_history')
    # ### end Alembic commands ###
