"""initial migration

Revision ID: 5bd3f384acea
Revises: 
Create Date: 2026-02-05 11:01:14.501692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd3f384acea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('function', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Float(), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('kwargs', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('state_history', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_history_created_at', 'job_history', ['created_at'], unique=False)
    op.create_index('ix_job_history_function', 'job_history', ['function'], unique=False)
    op.create_index('ix_job_history_status', 'job_history', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_history_status', table_name='job_history')
    op.drop_index('ix_job_history_function', table_name='job_history')
    op.drop_index('ix_job_history_created_at', table_name='job_history')
    op.drop_table('job_history')
    # ### end Alembic commands ###
