"""initial_schema

Revision ID: 98cc772f1591
Revises: 
Create Date: 2026-02-02 11:25:19.521469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98cc772f1591'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('queue', sa.String(length=64), nullable=False),
    sa.Column('function', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Float(), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('kwargs', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_history_created_at', 'job_history', ['created_at'], unique=False)
    op.create_index('ix_job_history_function', 'job_history', ['function'], unique=False)
    op.create_index('ix_job_history_status', 'job_history', ['status'], unique=False)
    op.create_index('ix_job_history_tenant_function', 'job_history', ['tenant_id', 'function'], unique=False)
    op.create_index('ix_job_history_tenant_id', 'job_history', ['tenant_id'], unique=False)
    op.create_index('ix_job_history_tenant_status', 'job_history', ['tenant_id', 'status'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_concurrent_jobs', sa.Integer(), nullable=False),
    sa.Column('max_jobs_per_minute', sa.Integer(), nullable=False),
    sa.Column('max_jobs_per_day', sa.Integer(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_tenant_api_key', 'tenants', ['api_key'], unique=False)
    op.create_index('ix_tenant_name', 'tenants', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tenant_name', table_name='tenants')
    op.drop_index('ix_tenant_api_key', table_name='tenants')
    op.drop_table('tenants')
    op.drop_index('ix_job_history_tenant_status', table_name='job_history')
    op.drop_index('ix_job_history_tenant_id', table_name='job_history')
    op.drop_index('ix_job_history_tenant_function', table_name='job_history')
    op.drop_index('ix_job_history_status', table_name='job_history')
    op.drop_index('ix_job_history_function', table_name='job_history')
    op.drop_index('ix_job_history_created_at', table_name='job_history')
    op.drop_table('job_history')
    # ### end Alembic commands ###
