"""add_state_history

Revision ID: e45523976727
Revises: 98cc772f1591
Create Date: 2026-02-02 11:37:23.184831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e45523976727'
down_revision: Union[str, Sequence[str], None] = '98cc772f1591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_history', sa.Column('state_history', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_history', 'state_history')
    # ### end Alembic commands ###
