"""Shared models for Conduit packages."""

from shared.api import API_PREFIX, HOURLY_BUCKET_TTL, MINUTE_BUCKET_TTL, REGISTRY_TTL
from shared.artifacts import ArtifactType
from shared.events import (
    BatchEventItem,
    BatchEventRequest,
    EventRequest,
    EventType,
    HealthResponse,
    JobCheckpointEvent,
    JobCompletedEvent,
    JobFailedEvent,
    JobProgressEvent,
    JobRetryingEvent,
    JobStartedEvent,
)
from shared.models import Job, JobStatus, StateTransition
from shared.patterns import get_matching_patterns, matches_event_pattern
from shared.schemas import (
    ApiDetailResponse,
    ApiEndpoint,
    ApiInfo,
    ApiInstance,
    ApisListResponse,
    ApiStats,
    ApiTrendHour,
    ApiTrendsResponse,
    ArtifactCreateResponse,
    ArtifactListResponse,
    ArtifactQueuedResponse,
    ArtifactResponse,
    CreateArtifactRequest,
    DashboardStats,
    EndpointsListResponse,
    ErrorResponse,
    FunctionDetailResponse,
    FunctionInfo,
    FunctionsListResponse,
    FunctionType,
    JobHistoryResponse,
    JobListResponse,
    JobStatsResponse,
    JobTrendHour,
    JobTrendsResponse,
    Run,
    RunStats,
    WorkerInfo,
    WorkerInstance,
    WorkersListResponse,
    WorkerStats,
)

__all__ = [
    # API tracking constants
    "API_PREFIX",
    "MINUTE_BUCKET_TTL",
    "HOURLY_BUCKET_TTL",
    "REGISTRY_TTL",
    # Core models
    "Job",
    "JobStatus",
    "StateTransition",
    # Events
    "EventType",
    "EventRequest",
    "BatchEventItem",
    "BatchEventRequest",
    "JobStartedEvent",
    "JobCompletedEvent",
    "JobFailedEvent",
    "JobRetryingEvent",
    "JobProgressEvent",
    "JobCheckpointEvent",
    # Artifacts
    "ArtifactType",
    "ArtifactCreateResponse",
    "ArtifactQueuedResponse",
    "ArtifactResponse",
    "ArtifactListResponse",
    "CreateArtifactRequest",
    "ErrorResponse",
    # Health
    "HealthResponse",
    # Pattern matching
    "matches_event_pattern",
    "get_matching_patterns",
    # API Schemas
    "ApiInstance",
    "ApiEndpoint",
    "ApiInfo",
    "ApisListResponse",
    "EndpointsListResponse",
    "ApiDetailResponse",
    "ApiTrendHour",
    "ApiTrendsResponse",
    "FunctionType",
    "Run",
    "WorkerInstance",
    "WorkerInfo",
    "WorkersListResponse",
    "WorkerStats",
    "FunctionInfo",
    "FunctionsListResponse",
    "FunctionDetailResponse",
    "RunStats",
    "ApiStats",
    "DashboardStats",
    # Job History
    "JobHistoryResponse",
    "JobListResponse",
    "JobStatsResponse",
    "JobTrendHour",
    "JobTrendsResponse",
]
